sonar.projectKey=Jayashan00_pulse-backend
sonar.organization=jayashan00
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,prisma/seed.js,infrastructure/**,Dockerfile,docker-compose*.yml